!Config

  LOGGING_LEVEL: "INFO"

  APP_NAME: "Ditto"
  DESCRIPTION: "Discord.py bot shell."
  VERSION: '1.0.0'

  TOKEN: !ENV 'TOKEN'

  PREFIXES:
    - "!"
  
  EXTENSIONS: 

    # Core Functionality
    'bot.cogs.core.admin': ~
    'bot.cogs.core.git': ~
    'bot.cogs.core.status': ~
    