!Config

  LOGGING_LEVEL: "INFO"

  APP_NAME: "Ditto"
  DESCRIPTION: "Discord.py bot shell."
  VERSION: '1.0.0'

  DONPHAN: !Config
    DSN: !ENV "POSTGRES_DSN"
    DELETE_TABLES_ON_STARTUP: no
    DELETE_VIEWS_ON_STARTUP: no
    APPLICATION_NAME: 'Ditto: Discord bot'

  TOKEN: !ENV 'TOKEN'

  PREFIXES:
    - "!"
  
  EXTENSIONS: 

    # Core Functionality
    'bot.cogs.core.admin': ~
    'bot.cogs.core.git': ~
    'bot.cogs.core.status': ~
    