!Config

  LOGGING_LEVEL: "INFO"

  APP_NAME: "Ditto"
  DESCRIPTION: "Discord.py bot shell."
  VERSION: '1.0.0'

  TOKEN: !ENV 'TOKEN'

  ERROR_LOG_CHANNEL: !Channel 1234567891234 1234567891234

  PREFIXES:
    - "!"
  
  EXTENSIONS: 

    # Core Functionality
    'bot.cogs.core.admin': ~
    'bot.cogs.core.git': ~
    'bot.cogs.core.status': ~
    
    # Metrics Functionality
    'bot.cogs.metrics': ~
    'bot.cogs.metrics.command_stats': ~
    'bot.cogs.metrics.socket_stats': ~